spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/auth/**,/admin/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**,/inventory/**
        - id: marketplace-service
          uri: lb://marketplace-service
          predicates:
            - Path=/marketplace/**
        # Refreshes
        - id: item-service-refresh
          uri: lb://item-service
          predicates:
            - Path=/item-service-refresh
          filters:
            - RewritePath=/item-service-refresh, /actuator/refresh
        - id: user-service-refresh
          uri: lb://user-service
          predicates:
            - Path=/user-service-refresh
          filters:
            - RewritePath=/user-service-refresh, /actuator/refresh
        - id: marketplace-service-refresh
          uri: lb://marketplace-service
          predicates:
            - Path=/marketplace-service-refresh
          filters:
            - RewritePath=/marketplace-service-refresh, /actuator/refresh
        # Swagger
        - id: item-openapi
          uri: lb://item-service
          predicates:
            - Path=/item-service/v3/api-docs, /item-service/swagger-ui/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka # для локального запуска