spring:
  application:
    name: item-service
  r2dbc:
    # url: r2dbc:postgresql://localhost:5432/game
    url: r2dbc:postgresql://postgres:5432/game1
    username: postgres
    password: moo748
  main:
    allow-circular-references: true
  flyway:
    user: postgres
    password: moo748
    schemas: public
    # url: jdbc:postgresql://localhost:5432/game
    url: jdbc:postgresql://postgres:5432/game1
    locations: db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka" # для локального запуска

# Refresh
management:
  endpoints:
    web:
      exposure:
        include: *