spring:
  application:
    name: item-service
  r2dbc:
    # url: r2dbc:postgresql://localhost:5432/game
    url: r2dbc:postgresql://postgres:5432/game
    username: postgres
    password: moo748
  # jpa:
  #   properties:
  #     hibernate:
  #       show_sql: true
  #   generate-ddl: false
  #   hibernate:
  #     ddl-auto: update
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/game
  #   username: postgres
  #   password: moo748
  #   driverClassName: org.postgresql.Driver
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka" # для локального запуска