spring:
  application:
    name: marketplace-service
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  datasource:
    # url: jdbc:postgresql://localhost:5432/game # для локального запуска
    url: jdbc:postgresql://postgres:5432/game
    username: postgres
    password: moo748
    driverClassName: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka # для локального запуска