spring:
  application:
    name: marketplace-service
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    # url: jdbc:postgresql://localhost:5432/game # для локального запуска
    url: jdbc:postgresql://postgres:5432/game
    username: postgres
    password: moo748
    driverClassName: org.postgresql.Driver
  flyway:
    user: postgres
    password: moo748
    schemas: public
    # url: jdbc:postgresql://localhost:5432/game
    url: jdbc:postgresql://postgres:5432/game
    locations: db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka # для локального запуска