spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    # url: jdbc:postgresql://localhost:5432/game # для локального запуска
    url: jdbc:postgresql://postgres:5432/game1
    username: postgres
    password: moo748
    driverClassName: org.postgresql.Driver
  main:
    allow-circular-references: true
  flyway:
    user: postgres
    password: moo748
    schemas: public
    # url: jdbc:postgresql://localhost:5432/game
    url: jdbc:postgresql://postgres:5432/game1
    locations: db/migration
    baseline-on-migrate: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  mail:
      host: smtp.gmail.com
      port: 587
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      username: jacksmithfromlondon@gmail.com
      password: ewrr fwka impn bzvp


security:
  jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 10m

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # http://localhost:8761/eureka # для локального запуска

# Refresh
management:
  endpoints:
    web:
      exposure:
        include: refresh